mv home-1-door-1.svg ep-home-1-door-1.svg
mv home-1-door-solid-1.svg ep-home-1-door-solid-1.svg
mv home-1-door-solid.svg ep-home-1-door-solid.svg
mv home-1-door.svg ep-home-1-door.svg
mv home-1-line-solid.svg ep-home-1-line-solid.svg
mv home-1-line.svg ep-home-1-line.svg
mv home-1-smile-solid.svg ep-home-1-smile-solid.svg
mv home-1-smile.svg ep-home-1-smile.svg
mv home-1-solid.svg ep-home-1-solid.svg
mv home-1-strip-solid.svg ep-home-1-strip-solid.svg
mv home-1-strip.svg ep-home-1-strip.svg
mv home-1.svg ep-home-1.svg
mv camera-2-solid.svg ep-camera-2-solid.svg
mv camera-2.svg ep-camera-2.svg
mv image-solid.svg ep-image-solid.svg
mv image.svg ep-image.svg
mv mic-off-solid.svg ep-mic-off-solid.svg
mv mic-off.svg ep-mic-off.svg
mv mic-solid.svg ep-mic-solid.svg
mv mic.svg ep-mic.svg
mv video-camera-1-solid.svg ep-video-camera-1-solid.svg
mv video-camera-1.svg ep-video-camera-1.svg
mv volume-down-solid.svg ep-volume-down-solid.svg
mv volume-down.svg ep-volume-down.svg
mv volume-mute-1-solid.svg ep-volume-mute-1-solid.svg
mv volume-mute-1.svg ep-volume-mute-1.svg
mv volume-mute-2-solid.svg ep-volume-mute-2-solid.svg
mv volume-mute-2.svg ep-volume-mute-2.svg
mv volume-up-solid.svg ep-volume-up-solid.svg
mv volume-up.svg ep-volume-up.svg
mv message-circle-solid.svg ep-message-circle-solid.svg
mv message-circle-text-solid.svg ep-message-circle-text-solid.svg
mv message-circle-text.svg ep-message-circle-text.svg
mv message-circle.svg ep-message-circle.svg
mv message-left-solid.svg ep-message-left-solid.svg
mv message-left-text-solid.svg ep-message-left-text-solid.svg
mv message-left-text.svg ep-message-left-text.svg
mv message-left.svg ep-message-left.svg
mv message-mid-solid.svg ep-message-mid-solid.svg
mv message-mid-text-solid.svg ep-message-mid-text-solid.svg
mv message-mid-text.svg ep-message-mid-text.svg
mv message-mid.svg ep-message-mid.svg
mv message-right-solid.svg ep-message-right-solid.svg
mv message-right-text-solid.svg ep-message-right-text-solid.svg
mv message-right-text.svg ep-message-right-text.svg
mv message-right.svg ep-message-right.svg
mv user-a-circle-solid.svg ep-user-a-circle-solid.svg
mv user-a-circle.svg ep-user-a-circle.svg
mv user-a-solid.svg ep-user-a-solid.svg
mv user-a-square-solid.svg ep-user-a-square-solid.svg
mv user-a-square.svg ep-user-a-square.svg
mv user-a.svg ep-user-a.svg
mv user-b-circle-solid.svg ep-user-b-circle-solid.svg
mv user-b-circle.svg ep-user-b-circle.svg
mv user-b-solid.svg ep-user-b-solid.svg
mv user-b-square-solid.svg ep-user-b-square-solid.svg
mv user-b-square.svg ep-user-b-square.svg
mv user-b.svg ep-user-b.svg
mv compass-1-solid.svg ep-compass-1-solid.svg
mv compass-1.svg ep-compass-1.svg
mv map-pin-2-solid.svg ep-map-pin-2-solid.svg
mv map-pin-2.svg ep-map-pin-2.svg
mv map-pin-3-solid.svg ep-map-pin-3-solid.svg
mv map-pin-3.svg ep-map-pin-3.svg
mv airplay-2-solid.svg ep-airplay-2-solid.svg
mv airplay-2.svg ep-airplay-2.svg
mv clock-1-solid.svg ep-clock-1-solid.svg
mv clock-1.svg ep-clock-1.svg
mv clock-stopwatch-2-solid.svg ep-clock-stopwatch-2-solid.svg
mv clock-stopwatch-2.svg ep-clock-stopwatch-2.svg
mv mouse-mini-1-solid.svg ep-mouse-mini-1-solid.svg
mv mouse-mini-1.svg ep-mouse-mini-1.svg
mv bill-1-solid.svg ep-bill-1-solid.svg
mv bill-1.svg ep-bill-1.svg
mv bookmark-solid.svg ep-bookmark-solid.svg
mv bookmark.svg ep-bookmark.svg
mv calendar-empty-solid.svg ep-calendar-empty-solid.svg
mv calendar-empty.svg ep-calendar-empty.svg
mv copyright-solid.svg ep-copyright-solid.svg
mv copyright.svg ep-copyright.svg
mv envelope-1-solid.svg ep-envelope-1-solid.svg
mv envelope-1.svg ep-envelope-1.svg
mv envelope-open-1-solid.svg ep-envelope-open-1-solid.svg
mv envelope-open-1.svg ep-envelope-open-1.svg
mv folder-1-search-solid.svg ep-folder-1-search-solid.svg
mv folder-1-search.svg ep-folder-1-search.svg
mv folder-1-solid.svg ep-folder-1-solid.svg
mv folder-1.svg ep-folder-1.svg
mv global-1-solid.svg ep-global-1-solid.svg
mv global-1.svg ep-global-1.svg
mv inbox-1-solid.svg ep-inbox-1-solid.svg
mv inbox-1.svg ep-inbox-1.svg
mv line-chart-1-box-solid.svg ep-line-chart-1-box-solid.svg
mv line-chart-1-box.svg ep-line-chart-1-box.svg
mv line-chart-2-box-solid.svg ep-line-chart-2-box-solid.svg
mv line-chart-2-box.svg ep-line-chart-2-box.svg
mv currency-dollar-circle-solid.svg ep-currency-dollar-circle-solid.svg
mv currency-dollar-circle.svg ep-currency-dollar-circle.svg
mv currency-dollar-solid.svg ep-currency-dollar-solid.svg
mv currency-dollar.svg ep-currency-dollar.svg
mv diamond-1-1.svg ep-diamond-1-1.svg
mv diamond-1-solid.svg ep-diamond-1-solid.svg
mv diamond-1.svg ep-diamond-1.svg
mv discount-1.svg ep-discount-1.svg
mv discount-solid.svg ep-discount-solid.svg
mv discount.svg ep-discount.svg
mv label-1-1.svg ep-label-1-1.svg
mv label-1-solid.svg ep-label-1-solid.svg
mv label-1.svg ep-label-1.svg
mv shopping-bag-2-solid.svg ep-shopping-bag-2-solid.svg
mv shopping-bag-2.svg ep-shopping-bag-2.svg
mv shopping-basket-2-1.svg ep-shopping-basket-2-1.svg
mv shopping-basket-2-solid.svg ep-shopping-basket-2-solid.svg
mv shopping-basket-2.svg ep-shopping-basket-2.svg
mv shopping-cart-1-1.svg ep-shopping-cart-1-1.svg
mv shopping-cart-1-solid.svg ep-shopping-cart-1-solid.svg
mv shopping-cart-1.svg ep-shopping-cart-1.svg
mv add-1.svg ep-add-1.svg
mv add-circle-1.svg ep-add-circle-1.svg
mv add-circle-solid.svg ep-add-circle-solid.svg
mv add-circle.svg ep-add-circle.svg
mv add-solid.svg ep-add-solid.svg
mv add.svg ep-add.svg
mv arrow-angle-down-1.svg ep-arrow-angle-down-1.svg
mv arrow-angle-down-circle-1.svg ep-arrow-angle-down-circle-1.svg
mv arrow-angle-down-circle-solid.svg ep-arrow-angle-down-circle-solid.svg
mv arrow-angle-down-circle.svg ep-arrow-angle-down-circle.svg
mv arrow-angle-down-solid.svg ep-arrow-angle-down-solid.svg
mv arrow-angle-down.svg ep-arrow-angle-down.svg
mv arrow-angle-left-1.svg ep-arrow-angle-left-1.svg
mv arrow-angle-left-circle-1.svg ep-arrow-angle-left-circle-1.svg
mv arrow-angle-left-circle-solid.svg ep-arrow-angle-left-circle-solid.svg
mv arrow-angle-left-circle.svg ep-arrow-angle-left-circle.svg
mv arrow-angle-left-solid.svg ep-arrow-angle-left-solid.svg
mv arrow-angle-left.svg ep-arrow-angle-left.svg
mv arrow-angle-right-1.svg ep-arrow-angle-right-1.svg
mv arrow-angle-right-circle-1.svg ep-arrow-angle-right-circle-1.svg
mv arrow-angle-right-circle-solid.svg ep-arrow-angle-right-circle-solid.svg
mv arrow-angle-right-circle.svg ep-arrow-angle-right-circle.svg
mv arrow-angle-right-solid.svg ep-arrow-angle-right-solid.svg
mv arrow-angle-right.svg ep-arrow-angle-right.svg
mv arrow-angle-up-1.svg ep-arrow-angle-up-1.svg
mv arrow-angle-up-circle-1.svg ep-arrow-angle-up-circle-1.svg
mv arrow-angle-up-circle-solid.svg ep-arrow-angle-up-circle-solid.svg
mv arrow-angle-up-circle.svg ep-arrow-angle-up-circle.svg
mv arrow-angle-up-solid.svg ep-arrow-angle-up-solid.svg
mv arrow-angle-up.svg ep-arrow-angle-up.svg
mv arrow-down-1.svg ep-arrow-down-1.svg
mv arrow-down-2.svg ep-arrow-down-2.svg
mv arrow-down-3.svg ep-arrow-down-3.svg
mv arrow-down-solid-1.svg ep-arrow-down-solid-1.svg
mv arrow-down-solid.svg ep-arrow-down-solid.svg
mv arrow-down.svg ep-arrow-down.svg
mv arrow-left-1.svg ep-arrow-left-1.svg
mv arrow-left-2.svg ep-arrow-left-2.svg
mv arrow-left-3.svg ep-arrow-left-3.svg
mv arrow-left-solid-1.svg ep-arrow-left-solid-1.svg
mv arrow-left-solid.svg ep-arrow-left-solid.svg
mv arrow-left.svg ep-arrow-left.svg
mv arrow-right-1.svg ep-arrow-right-1.svg
mv arrow-right-2.svg ep-arrow-right-2.svg
mv arrow-right-3.svg ep-arrow-right-3.svg
mv arrow-right-solid-1.svg ep-arrow-right-solid-1.svg
mv arrow-right-solid.svg ep-arrow-right-solid.svg
mv arrow-right.svg ep-arrow-right.svg
mv arrow-up-1.svg ep-arrow-up-1.svg
mv arrow-up-2.svg ep-arrow-up-2.svg
mv arrow-up-3.svg ep-arrow-up-3.svg
mv arrow-up-solid-1.svg ep-arrow-up-solid-1.svg
mv arrow-up-solid.svg ep-arrow-up-solid.svg
mv arrow-up.svg ep-arrow-up.svg
mv bell-2-1.svg ep-bell-2-1.svg
mv bell-2-notification-1.svg ep-bell-2-notification-1.svg
mv bell-2-notification-solid.svg ep-bell-2-notification-solid.svg
mv bell-2-notification.svg ep-bell-2-notification.svg
mv bell-2-ring-1.svg ep-bell-2-ring-1.svg
mv bell-2-ring-solid.svg ep-bell-2-ring-solid.svg
mv bell-2-ring.svg ep-bell-2-ring.svg
mv bell-2-slash-1.svg ep-bell-2-slash-1.svg
mv bell-2-slash-solid.svg ep-bell-2-slash-solid.svg
mv bell-2-slash.svg ep-bell-2-slash.svg
mv bell-2-solid.svg ep-bell-2-solid.svg
mv bell-2.svg ep-bell-2.svg
mv check-1.svg ep-check-1.svg
mv check-circle-1.svg ep-check-circle-1.svg
mv check-circle-solid.svg ep-check-circle-solid.svg
mv check-circle.svg ep-check-circle.svg
mv check-solid.svg ep-check-solid.svg
mv check.svg ep-check.svg
mv cross-1.svg ep-cross-1.svg
mv cross-circle-1.svg ep-cross-circle-1.svg
mv cross-circle-solid.svg ep-cross-circle-solid.svg
mv cross-circle.svg ep-cross-circle.svg
mv cross-solid.svg ep-cross-solid.svg
mv cross.svg ep-cross.svg
mv minus-1.svg ep-minus-1.svg
mv minus-circle-1.svg ep-minus-circle-1.svg
mv minus-circle-solid.svg ep-minus-circle-solid.svg
mv minus-circle.svg ep-minus-circle.svg
mv minus-solid.svg ep-minus-solid.svg
mv minus.svg ep-minus.svg
mv search-2-1.svg ep-search-2-1.svg
mv search-2-solid.svg ep-search-2-solid.svg
mv search-2.svg ep-search-2.svg
mv settings-2-mini-1.svg ep-settings-2-mini-1.svg
mv settings-2-mini-solid.svg ep-settings-2-mini-solid.svg
mv settings-2-mini.svg ep-settings-2-mini.svg
mv zoom-in-1.svg ep-zoom-in-1.svg
mv zoom-in-solid.svg ep-zoom-in-solid.svg
mv zoom-in.svg ep-zoom-in.svg
mv zoom-out-1.svg ep-zoom-out-1.svg
mv zoom-out-solid.svg ep-zoom-out-solid.svg
mv zoom-out.svg ep-zoom-out.svg
